ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install dependencies
RUN python3 -m pip install -U numpy==1.26
RUN python3 -m pip install -U lightning
RUN python3 -m pip install -U scikit-image

RUN python3 -m pip install -U rosbags
RUN python3 -m pip install -U rosbags-image

RUN python3 -m pip install -U tensorboard
RUN python3 -m pip install -U labelbox
