services:
  ros2:
    image: isaac_ros_dev-x86_64
    container_name: a2rl_container
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    runtime: nvidia
    privileged: true
    restart: always
    shm_size: '2gb'
    volumes:
      # display related 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
      # ssh related
      # - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK:ro
      # git
      - ~/.gitconfig:/root/.gitconfig_local
      # working dirs
      # - ~/aerostack2_ws:/root/aerostack2_ws
      - ~/TFM_david/gate_detector:/root/gate_detector
      - ~/Documents/rosbag_a2rl:/root/rosbag_a2rl
      - ~/project_a2rl:/root/project_a2rl
      - ~/drone-racing-dataset:/root/drone-racing-dataset
      - ~/drone-racing-msgs:/root/aerostack2_ws/src/drone-racing-msgs
      - ~/gate_perception:/root/aerostack2_ws/src/gate_perception
      # oh-my-bash
      - ~/.oh-my-bash:/root/.oh-my-bash
    network_mode: "host"
    command: tail -f /dev/null
    working_dir: /root
